### ISSUE TITLE
CFGrote's JOSS Review

### ISSUE THREAD

**Issue by CFGrote** [Isurwars/Correlation#7]
Hi @Isurwars.
First off, great work and very useful. Please find my comments and notes while working on the JOSS Review checklist https://github.com/openjournals/joss-reviews/issues/2976.

#### Installation
* There is no `configure` step involved which means if I had non-standard settings on my computer, `make` might fail to locate the compiler and/or libraries. Also, installing into a target directory is not supported (no install target).
* You could explain why the user should run `make clean` **after** building.
* The binary produced by the `make all` step has the windows-typical '.exe' extension. This is a bit unusual for linux/mac.
#### Functionality
* `make tests` produces no errors, however it remains unclear if that just means the program ends or if it actually passed unittest and/or regression tests. Probably related to #5. 
* Running the individual test with `./bin/correlation.exe test/test_1/aPd.cell`
  returns "File not found". aPd.cell is in test_3, test run is ok. 
* Plotting the resulting PDF from test_3 gives the following figure:
![Figure_1](https://user-images.githubusercontent.com/15476807/108195232-ca784c00-7117-11eb-9684-64e887df2ac6.png).
 You might consider putting this or a similar graph into the README and instruct the user to try and reproduce this result as a confirmation the code works as it should.
* Performance: You claim that your code can handle up to 25000 atoms. I could not find a demonstration of such a system. Is it in test_6? If so, you should clearly mention it.

#### Documentation
* I find the output not properly documented (neither in the paper nor in the README): Describe the content of each file, describe what each column contains and specify the units. At a minimum, this information should go into the header of each .csv file. As a perspective, I recommend storing the results in a self-documenting format, e.g. hdf5.
* You should document the command line options in the README.
* No automated tests, see comment above. Adding tests that compare the code's output to reference data will make the validity of your code more accessible.
* No community guidelines (probably related to #6)

#### Paper
* Summary:
    * You state that the code is ready for mac while the README says mac not supported due to compiler issues.
    * A non-expert reader will be overwhelmed by the technical and field specific jargon. I advise to write something like: "Our code calculates various correlation functions from atomic positions".
    * Your claimed limit of 25000 atoms is not a lot (e.g. in biomolecules). What causes this limit? Does it depend on hardware/software on the user's system?
* Statement of need: 
    * name and cite other packages (earlier, in statement of need). Please check the exhaustive list of software in the Computational Physics Communications archive http://cpc.cs.qub.ac.uk/, the IUCr's software list https://www.iucr.org/resources/other-directories/software for similar software. What is particular about your software that makes it stand out from other packages?
    * clearly name target audience
* Benchmarks, validation:
    * define test_x as being included in the software package. a table with
      references would be helpful. 
    * Is test_6 really a challenge? it completes on my laptop in a few
      seconds. What are the limiting factors? memory/cpu? What exactly do you mean 
      by "... benchmark  memory and CPU performance ...". The sentence on line 91-93 mentions test_6 and test_4, it is not clear which one you refer to here.
* Conclusion:
    * You mention HPC here but HTC (high throughput computing) earlier. What exactly do you mean here? Does your code support parallelization using e.g. MPI or similar frameworks? Suppose I want to run a large system that does not fit into memory, can your code deal with it? How do you address parallel IO?
    * How will it be extended, which features are missing?

**Comment by jgostick** [comment]
@CFGrote, this is superb review!  I think the authors of the package will be very appreciative of your efforts.

**Comment by Isurwars** [comment]
Currently workingon the response and incorporating the recommendations made by @CFGrote, Thanks for the fantastic review.

**Comment by CFGrote** [comment]
I'll make new issues for each further comment, would appreciate if the discussion continues there.
- [ ] typo in test report (#10)
- [ ] typo in readme (#11)
- [ ] Output file documentation (units missing) (#12)
- [ ] 25000 atoms (#13)
- [ ] HPC vs. HTC (#14)
- [ ] Statement of need: Comment not addressed (#15)
- [ ] List of improvements into paper.md (#16)

**Comment by Isurwars** [comment]
Most of these issues were fixed in RC6 and RC7.

Hope we can proceed with the article release.

**Comment by Isurwars** [comment]
Professor Valladares (Group leader) and I consider that editor and reviewer's suggestions improve the code and the paper enough to be considered as great contributors to the project. 

How should I incorporate them in the paper.md and the AUTHORS files, as co-authors?

**Comment by CFGrote** [comment]
Thanks for your kind offer, @Isurwars. You are the author and should
take full credit for it. I only did my job as a reviewer. Feel free to
acknowledge this in the paper and/or repo, e.g. in a Acknowledgements
section, but I'd rather not become a co-author.

**Comment by CFGrote** [comment]
> Most of these issues were fixed in RC6 and RC7.
> 
> Hope we can proceed with the article release.

it would be extremely helpful if you could comment in the linked issues and attach the commit hash that fixed the issue. thanks!

**Comment by Isurwars** [comment]
Understood, will reference the issues in my next comment, currently making the list.

**Comment by Isurwars** [comment]
Sorry for the delay in the answer, these has been a rough weeks in my personal life, and I have been in and out of the hospital.

I will answer the petitions and requests as soon as I can.

**Comment by jgostick** [comment]
noted...we can wait.

**Comment by Isurwars** [comment]
The last request has been adresss in RC8, and RC9. Hope we can move the paper foward.
